### ISSUE TITLE
Skill not running.

### ISSUE THREAD

**Issue by AnushPatel** [alexa/skill-sample-nodejs-name-the-show#3]
When running on the ASK Simulator I get the 'There was a problem with the requested skill's response' error with the JSON output being 'null' 

When running on Lambda's testing facility with the JSON input from the ASK Simulator gives the following error:
```
{
  "errorMessage": "RequestId: 8404d481-dacd-11e8-8fc3-c159553de89b Process exited before completing request"
}
```

Any ideas on how to fix this?

**Comment by memodoring** [comment]
That error means that the lambda function did not return an object before closing. Check your stack trace in CloudWatch as there might be a syntax error in your code.

**Comment by AnushPatel** [comment]
Thanks for replying Memo! I have managed to load the logs up and this is the main error 
`2018-10-28T16:35:37.349Z	7f2d2347-dacf-11e8-ba68-63920481d402	AskSdk.DynamoDbPersistenceAdapter Error: Could not create table (NameTheShow): User: arn:aws:sts::278930706417:assumed-role/ask-lambda-Name-The-Show/ask-name-the-show is not authorized to perform: dynamodb:CreateTable on resource: arn:aws:dynamodb:us-east-1:278930706417:table/NameTheShow
at Object.createAskSdkError (/var/task/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/utils/AskSdkUtils.js:22:17)
at Response.<anonymous> (/var/task/node_modules/ask-sdk-dynamodb-persistence-adapter/dist/attributes/persistence/DynamoDbPersistenceAdapter.js:88:41)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)`

Does this skill use dynamodb?

**Comment by memodoring** [comment]
Yes. You’ll need to make sure your role has the right permissions. The error above is saying you can’t create a dynamo ramble

**Comment by AnushPatel** [comment]
Oh I see! Let me see what happens when I set my IAM to full admin.. (Is that right?)

Sorry - Im a bit of a noob!

**Comment by franklin-lobb** [comment]
Best practice is to only grant the necessary permissions, but full admin will work.  Note that the first time you run it after making the change you will still get an error -- that triggers the table creation process.  Give it a few minutes (or less) and try again.  If you want to check the progress of creating the table, look in the DynamoDB section of the AWS Console.

I added the details of how to add the right permissions to the Read Me.

**Comment by AnushPatel** [comment]
That has fixed it! Thank you very much :)

**Comment by ylorgat** [comment]
Hi there,

I'm just reopening this issue because I'm running into the same problem and don't really know how to fix it unfortunately. 

So I'm creating an Alexa Hosted Skill and I want it to communicate to a DynamoDB hosted using my own AWS Resources unless there's a better way to connect a dynamoDB but I can't find another way. 

in cloudwatch this is the error that i get

AccessDeniedException: User: arn:aws:sts::31xxxxxx:assumed-role/AlexaHostedSkillLambdaRole/c0724461-xxxxx is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:eu-west-1:31xxxxxx:table/timetable

DynamoDB is not hosted in the Alexa Hosted AWS Account which has a username of VoiceHubSSORole/VoiceHubSSORole.

I hope you can help me with this issue. 

Thank you very much

**Comment by franklin-lobb** [comment]
@ylorgat The issue you're experiencing is probably very different, even tho' it's still a DDB access issue.  Check out these instructions for the cross account access to a DynamoDB table: https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#personal

If this doesn't solve it, I'd suggest opening a new issue. If you want to tag me on it, I can help.
